### ISSUE TITLE
Remembering or guessing just once

### ISSUE THREAD

**Issue by ByteHamster** [beltrachi/automatic_dictionary#11]
The add-on is just working once after restarting Thunderbird: Just the first reply, first compose and first forward.

- Click "write message" (or reply or forward)
- Compose window opens
- Write receiver address
- AD sets the locale
- Close the window
- Click "write message" again (or reply or forward)
- Compose window opens
- Write receiver address
- AD does nothing

Maybe this post can help because it's the same behavior: A script does its action in compose window just once.
http://stackoverflow.com/questions/7414032/thunderbird-extension-load-event-seems-to-occur-only-once

OS: Windows 8.1
Thunderbird 24.4.0
![image](https://cloud.githubusercontent.com/assets/5811634/3216787/8f5a506e-efd7-11e3-8ffc-7803dbaf22bd.png)

**Comment by beltrachi** [comment]
Hi ByteHamster!

Is it working for you in the last Thunderbird? (31.3.0)

I just checked it in the same setup (W81, plugins, etc.) but in Thunderbird 31.3.0 (I can't find where to download 24.4.0) and following the same steps as you explained and here is my reply:

- It works as expected in the steps you described. The AD does not say or do anything when the dictionary locale is in the language that the receiver email should have. This is what happens when you say "AD does nothing". The AD detects the recipient but it does nothing because the spellchecker has the right language setting.

In case it's still not working for you, I suggest you to send me a log of what is happening in your case. I prepared a version that logs all behaviour of the plugin (anonymously, hiding emails) and send me the log after. 

The version with this feature is here https://github.com/beltrachi/automatic_dictionary/raw/v1.7.0/automatic_dictionary.xpi (its not officialy released yet) and do the following:
1. Go to preferences of the plugin (in Thunderbird > Addons > Automatic Dictionary > Preferences)
2. Activate "Save log to file"
3. Set Log level to "Debug"
4. Restart thunderbird
5. Reproduce the case that do not work
6. Go to Automatic Dictionary preferences and click on "Send log to developer"
7. After that, disable the "Save to log file" and set Log level back to "Warning".

With that log, I'll have more information and may be able to see what's happening.

**Comment by ByteHamster** [comment]
Ah, forgot that one. The problem is still happening. Just played around a bit and noticed the following strange behavior:

* Restart Thunderbird
* Select mail with German receiver
* Press Reply
* Compose window opens
* AD guesses German
* Close compose window
* Select mail with English receiver
* Press Reply
* Compose window opens
* AD does not seem to do anything, no notification etc
* Minimize compose window
* Restore compose window
* AD remembers English
* Minimizing again has no further effect

I am going to do exactly these actions and send you the log.
