### ISSUE TITLE
Dictionary change not triggered when replying

### ISSUE THREAD

**Issue by SimonSapin** [beltrachi/automatic_dictionary#13]
The extension seems to have stopped doing anything for me. This **might** be since I updated to Thunderbird 31.5.0.

**Comment by beltrachi** [comment]
Hi,

I've just installed 31.5.0 and it's working.

Does appear anything on the error console? 
Error console is in "Tools" > "Error console" (Ctrl+shift+j)

Or maybe you have disabled the "Enable spellcheck as you type" ?
Its on "Edit" > "Preferences" > "Composition" > "Spelling"
It has to be enabled.

If it's not working either, can you try to install the next version? Maybe your issue is fixed:
https://github.com/beltrachi/automatic_dictionary/raw/master/automatic_dictionary.xpi

**Comment by SimonSapin** [comment]
Sorry for the poor issue report. The extension is still working, so this is probably not related to 31.5.0.

What I’m seeing is that when hitting the Reply button on an email, the dictionary is not checked against the automatically-filled recipient at first. I can compose a message and send it without triggering the extension. The extension does trigger and changes the dictionary when I click inside (give focus to) the list of recipients, even without modifying it.

**Comment by beltrachi** [comment]
I understand your issue.

Have you tried new beta version? It could fix your issue.

If not, tell me how to reproduce it because it's working in my case.
- Operating system
- Thunderbird version: 31.5.0 in your case
- Plugins installed (some snapshots on addons tab would be enough)
- Steps to reproduce. In your case it should not be required.

Thanks for collaborating!

Best

**Comment by SimonSapin** [comment]
Automatic Dictionary version: 1.5.5. I haven’t tried beta. How can I get it?

Thunderbird 31.5.0 on Archlinux x86_64. Extensions and plugins:

<img src=https://cloud.githubusercontent.com/assets/291359/6516357/92c8060e-c391-11e4-9c12-2a316dd02e91.png width="48%"> <img src=https://cloud.githubusercontent.com/assets/291359/6516388/c326bb10-c391-11e4-93dd-27478695fa76.png width="48%">

Steps to reproduce (I’m using English and French but any two language probably do the same):

* Make sure that the extension saves a preference for French for recipient A.
* In the compose window, change the dictionary to English. Close the compose window.
* (If you click the Write button now, starting a new message with no recipient, the dictionary defaults to English, the last one used.)
* Find a message from contact A
* Click Reply

Expected result: the dictionary is changed to French per the saved preference, and there is a popup near the status bar of the compose window that says so.

Actual result: the dictionary stays in English, and most of the quoted text (in French) is underlined with the “spelling error” red squiggle. If focus is given to the recipient list or the subject line (as oppose to the message’s body), only then the dictionary is correctly changed and the popup appears.

**Comment by beltrachi** [comment]
Could you try the new version? 

https://github.com/beltrachi/automatic_dictionary/raw/v1.7.1/automatic_dictionary.xpi

Tell me if it fixes your issue please :)

**Comment by SimonSapin** [comment]
I didn’t manage to reproduce the issue (at least the “usual” way) on 1.7.1, looks like it’s fixed.

**Comment by beltrachi** [comment]
Great! Thanks for your feedback!
