### ISSUE TITLE
1.8.2: Notifications inconsistent (maybe a feature not a bug)

### ISSUE THREAD

**Issue by jorgk3** [beltrachi/automatic_dictionary#19]
Start a new message to a recipient with a saved language.
Notification received: AutomaticDictionary: Remembered <dict>.
Start another message to the same recipient.
No notification received.
Start a message to a different recipient with a saved language. Notification received.
Start another message to the first recipient. Notification received.

So the second and subsequent message to the same recipient doesn't receive a notification.
Feature or bug?

Also, the corresponding term to "save" is "restore". To use "remember" for the process of setting the language from a saved preference seems confusing to me. Of course the language was saved (remembered) before, but now it's retrieved from the "memory" and set or restored.

**Comment by beltrachi** [comment]
For the first part, the behavior is because it only shows notification when it changes the language, not when the language is the same used in that moment. It's inteded. I do not want to bother more than necessary or only when it actually does something.

The second part, I'll think about it. I agree that "Rembember" is not the best choice. I'll keep you posted.

**Comment by jorgk3** [comment]
Closing this, since the different notifications are a feature.
